[phases.setup]
nixPkgs = ["python312", "gcc", "postgresql"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install uv",
  "uv sync --frozen"
]

[phases.build]
cmds = ["echo 'No build step needed for API'"]

[start]
cmd = "uv run app.py"
